// tslint:disable max-file-line-count

export {
    computeTotalPitchValueContourValue,
    pitchValueRest,
} from './contours'
export {
    computeNotesValueIndexSum,
    computeNotesValueScalarSum,
} from './notes'
export {
    materializeStandardScales,
    computeNonScale,
    computeFlatValuesScale,
    computeHarmonicSeriesScale,
    computeSubharmonicSeriesScale,
} from './scales'
export {
    PitchCircularTechnique,
    pitchCirculate,
} from './custom'

export {
    Segment,
    Rendering,
    RenderingByBlockElement,
    PitchOnly,
    ValueOnly,
    IntensityOnly,
    SustainOnly,
    XOnly,
    XYOnly,
    XYZOnly,
    ScaleOnly,
    PitchValue,
    PitchIntensity,
    PitchSustain,
    PitchX,
    PitchXY,
    PitchXYZ,
    PitchScale,
    ValueIntensity,
    ValueSustain,
    ValueX,
    ValueXY,
    ValueXYZ,
    ValueScale,
    IntensitySustain,
    IntensityX,
    IntensityXY,
    IntensityXYZ,
    IntensityScale,
    SustainX,
    SustainXY,
    SustainXYZ,
    SustainScale,
    XScale,
    XYScale,
    XYZScale,
    PitchValueIntensity,
    PitchValueSustain,
    PitchValueX,
    PitchValueXY,
    PitchValueXYZ,
    PitchValueScale,
    PitchIntensitySustain,
    PitchIntensityX,
    PitchIntensityXY,
    PitchIntensityXYZ,
    PitchIntensityScale,
    PitchSustainX,
    PitchSustainXY,
    PitchSustainXYZ,
    PitchSustainScale,
    PitchXScale,
    PitchXYScale,
    PitchXYZScale,
    ValueIntensitySustain,
    ValueIntensityX,
    ValueIntensityXY,
    ValueIntensityXYZ,
    ValueIntensityScale,
    ValueXScale,
    ValueXYScale,
    ValueXYZScale,
    IntensitySustainX,
    IntensitySustainXY,
    IntensitySustainXYZ,
    IntensitySustainScale,
    IntensityXScale,
    IntensityXYScale,
    IntensityXYZScale,
    SustainXScale,
    SustainXYScale,
    SustainXYZScale,
    PitchValueIntensitySustain,
    PitchValueIntensityX,
    PitchValueIntensityXY,
    PitchValueIntensityXYZ,
    PitchValueIntensityScale,
    PitchValueSustainX,
    PitchValueSustainXY,
    PitchValueSustainXYZ,
    PitchValueXScale,
    PitchValueXYScale,
    PitchValueXYZScale,
    PitchIntensitySustainX,
    PitchIntensitySustainXY,
    PitchIntensitySustainXYZ,
    PitchIntensitySustainScale,
    PitchIntensityXScale,
    PitchIntensityXYScale,
    PitchIntensityXYZScale,
    PitchSustainXScale,
    PitchSustainXYScale,
    PitchSustainXYZScale,
    ValueIntensitySustainX,
    ValueIntensitySustainXY,
    ValueIntensitySustainXYZ,
    ValueIntensitySustainScale,
    ValueIntensityXScale,
    ValueIntensityXYScale,
    ValueIntensityXYZScale,
    ValueSustainXScale,
    ValueSustainXYScale,
    ValueSustainXYZScale,
    IntensitySustainXScale,
    IntensitySustainXYScale,
    IntensitySustainXYZScale,
    PitchValueIntensitySustainX,
    PitchValueIntensitySustainXY,
    PitchValueIntensitySustainXYZ,
    PitchValueIntensitySustainScale,
    PitchValueIntensityXScale,
    PitchValueIntensityXYScale,
    PitchValueIntensityXYZScale,
    PitchValueSustainXScale,
    PitchValueSustainXYScale,
    PitchValueSustainXYZScale,
    PitchIntensitySustainXScale,
    PitchIntensitySustainXYScale,
    PitchIntensitySustainXYZScale,
    ValueIntensitySustainXScale,
    ValueIntensitySustainXYScale,
    ValueIntensitySustainXYZScale,
    PitchValueIntensitySustainXScale,
    PitchValueIntensitySustainXYScale,
    PitchValueIntensitySustainXYZScale,
} from './types'

export {
    STANDARD_DURATION_SCALE_INDEX,
    STANDARD_PITCH_SCALE_INDEX,
    FULL_GAIN,
    SILENT,
    STANDARD_PITCH_INDEX_INDICATING_REST,
} from './constants'
