// tslint:disable max-file-line-count

export {
    computeTotalPitchValueContourValue,
    pitchValueRest,
} from './contours'
export {
    computeNotesValueIndexSum,
    computeNotesValueScalarSum,
} from './notes'
export {
    materializeStandardScales,
    computeNonScale,
    thunkFlatValueScale,
    computeHarmonicSeriesScale,
    computeSubharmonicSeriesScale,
} from './scales'
export {
    PitchCircularTechnique,
    pitchCirculate,
} from './custom'

export {
    ENOUGH_HARMONIC_SERIES_STEPS_TO_LEAVE_HUMAN_HEARING_RANGE_FROM_THREE_OCTAVES_BELOW_PITCH_STANDARD,
} from './constants'

export {
    Segment,
    Rendering,
    RenderingByBlockElement,
    PitchOnly,
    ValueOnly,
    IntensityOnly,
    EnvelopeOnly,
    XOnly,
    XYOnly,
    XYZOnly,
    ScaleOnly,
    PitchValue,
    PitchIntensity,
    PitchEnvelope,
    PitchX,
    PitchXY,
    PitchXYZ,
    PitchScale,
    ValueIntensity,
    ValueEnvelope,
    ValueX,
    ValueXY,
    ValueXYZ,
    ValueScale,
    IntensityEnvelope,
    IntensityX,
    IntensityXY,
    IntensityXYZ,
    IntensityScale,
    EnvelopeX,
    EnvelopeXY,
    EnvelopeXYZ,
    EnvelopeScale,
    XScale,
    XYScale,
    XYZScale,
    PitchValueIntensity,
    PitchValueEnvelope,
    PitchValueX,
    PitchValueXY,
    PitchValueXYZ,
    PitchValueScale,
    PitchIntensityEnvelope,
    PitchIntensityX,
    PitchIntensityXY,
    PitchIntensityXYZ,
    PitchIntensityScale,
    PitchEnvelopeX,
    PitchEnvelopeXY,
    PitchEnvelopeXYZ,
    PitchEnvelopeScale,
    PitchXScale,
    PitchXYScale,
    PitchXYZScale,
    ValueIntensityEnvelope,
    ValueIntensityX,
    ValueIntensityXY,
    ValueIntensityXYZ,
    ValueIntensityScale,
    ValueXScale,
    ValueXYScale,
    ValueXYZScale,
    IntensityEnvelopeX,
    IntensityEnvelopeXY,
    IntensityEnvelopeXYZ,
    IntensityEnvelopeScale,
    IntensityXScale,
    IntensityXYScale,
    IntensityXYZScale,
    EnvelopeXScale,
    EnvelopeXYScale,
    EnvelopeXYZScale,
    PitchValueIntensityEnvelope,
    PitchValueIntensityX,
    PitchValueIntensityXY,
    PitchValueIntensityXYZ,
    PitchValueIntensityScale,
    PitchValueEnvelopeX,
    PitchValueEnvelopeXY,
    PitchValueEnvelopeXYZ,
    PitchValueXScale,
    PitchValueXYScale,
    PitchValueXYZScale,
    PitchIntensityEnvelopeX,
    PitchIntensityEnvelopeXY,
    PitchIntensityEnvelopeXYZ,
    PitchIntensityEnvelopeScale,
    PitchIntensityXScale,
    PitchIntensityXYScale,
    PitchIntensityXYZScale,
    PitchEnvelopeXScale,
    PitchEnvelopeXYScale,
    PitchEnvelopeXYZScale,
    ValueIntensityEnvelopeX,
    ValueIntensityEnvelopeXY,
    ValueIntensityEnvelopeXYZ,
    ValueIntensityEnvelopeScale,
    ValueIntensityXScale,
    ValueIntensityXYScale,
    ValueIntensityXYZScale,
    ValueEnvelopeXScale,
    ValueEnvelopeXYScale,
    ValueEnvelopeXYZScale,
    IntensityEnvelopeXScale,
    IntensityEnvelopeXYScale,
    IntensityEnvelopeXYZScale,
    PitchValueIntensityEnvelopeX,
    PitchValueIntensityEnvelopeXY,
    PitchValueIntensityEnvelopeXYZ,
    PitchValueIntensityEnvelopeScale,
    PitchValueIntensityXScale,
    PitchValueIntensityXYScale,
    PitchValueIntensityXYZScale,
    PitchValueEnvelopeXScale,
    PitchValueEnvelopeXYScale,
    PitchValueEnvelopeXYZScale,
    PitchIntensityEnvelopeXScale,
    PitchIntensityEnvelopeXYScale,
    PitchIntensityEnvelopeXYZScale,
    ValueIntensityEnvelopeXScale,
    ValueIntensityEnvelopeXYScale,
    ValueIntensityEnvelopeXYZScale,
    PitchValueIntensityEnvelopeXScale,
    PitchValueIntensityEnvelopeXYScale,
    PitchValueIntensityEnvelopeXYZScale,
} from './types'

export {
    FULL_GAIN,
    SILENT,
    STANDARD_PITCH_INDEX_INDICATING_REST,
} from './constants'
